# 가져올 이미지를 정의
FROM node:14-alpine

# 경로 설정하기
WORKDIR /app

# package.json과 package-lock.json을 워킹 디렉토리에 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 현재 디렉토리의 모든 파일을 도커 컨테이너의 워킹 디렉토리에 복사한다.
COPY . .

# 3000번 포트 노출
EXPOSE 3000

# npm start 스크립트 실행
CMD ["npm", "start"]
