spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret

server:
  env: blue

---
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue
  security:
    oauth2:
      client:
        kakao:
          redirect-uri: http://54.180.132.230/login/oauth2/code/kakao
        naver:
          redirect-uri: http://54.180.132.230/login/oauth2/code/naver

server:
  port: 8080
  serverAddress: 54.180.132.230

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green
  security:
    oauth2:
      client:
        kakao:
          redirect-uri: http://54.180.132.230/login/oauth2/code/kakao
        naver:
          redirect-uri: http://54.180.132.230/login/oauth2/code/naver

server:
  port: 8081
  serverAddress: 54.180.132.230

serverName: green_server

---


jwt:
    access-expire-time: ${ACCESS_EXPIRE_TIME}
    key: ${JWT_SECRET_KEY}
    refresh-expire-time: ${REFRESH_EXPIRE_TIME}
server:
    port: 8080
spring:
    application:
        name: eleven-book
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${MYSQL_PASSWORD}
        url: jdbc:mysql://127.0.0.1:${MYSQL_PORT}/${MYSQL_DATABASE}
        username: ${MYSQL_USER}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                default_batch_fetch_size: 1000
                format_sql: true
                show_sql: true
                use_sql_comments: true
    config:
      activate:
        on-profile: common
    security:
        oauth2:
            client:
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-info-authentication-method: header
                        user-name-attribute: id
                    naver:
                      authorization-uri: https://nid.naver.com/oauth2.0/authorize
                      token-uri: https://nid.naver.com/oauth2.0/token
                      user-info-uri: https://openapi.naver.com/v1/nid/me
                      user-info-authentication-method: header
                      user-name-attribute: response
                registration:
                    google:
                        client-id: ${SOCIAL_GOOGLE_CLIENT_ID}
                        client-secret: ${SOCIAL_GOOGLE_CLIENT_SECRET}
                        scope:
                            - email
                    kakao:
                      client-id: ${SOCIAL_KAKAO_CLIENT_ID}
                      client-secret: ${SOCIAL_KAKAO_CLIENT_SECRET}
                      client-authentication-method: client_secret_post
                      authorization-grant-type: authorization_code
                      scope:
                        - account_email
                      redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                      client-name: Kakao
                      provider: kakao
                    naver:
                      client-id: ${SOCIAL_NAVER_CLIENT_ID}
                      client-secret: ${SOCIAL_NAVER_CLIENT_SECRET}
                      client-authentication-method: client_secret_post
                      authorization-grant-type: authorization_code
                      redirect-uri: http://localhost:8080/login/oauth2/code/naver
                      scope:
                        - email
                      client-name: Naver
