### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "username": "master2",
  "password": "1234",
  "email": "test1@gmail.com"
}

### login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "master",
  "password": "1234"
}

> {%
    client.global.set("access_token", response.body.accessToken);
%}

### logout
PATCH localhost:8080/api/auth/logout
Authorization:{{access_token}}


### 유저
GET localhost:8080/api/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrYWthb18zNTIzMDgxNDEyIiwiaWF0IjoxNzIxOTk1Mjk4LCLthqDtgbBf7IOd7ISxX-2DnOyKpO2KuCI6Iu2DnOyKpO2KuCIsImV4cCI6MTcyMjAwMTI5OH0.iwWc1oYKEBpF81b_9zsX9fUiPt4YgztN8NVDwZutXIc