### 회원가입
POST http://localhost:8080/user/signup
Content-Type: application/json

{
  "username": "username",
  "password": "password@1234",
  "email": "test1@gmail.com"
}

### login
POST localhost:8080/auth/login
Content-Type: application/json

{
  "username": "username2",
  "password": "password@1234"
}

> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}


### 로그아웃
PATCH http://localhost:8080/auth/refresh
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrYWthb18zNTIzMDgxNDEyIiwiaWF0IjoxNzIxOTk1Mjk4LCLthqDtgbBf7IOd7ISxX-2DnOyKpO2KuCI6Iu2DnOyKpO2KuCIsImV4cCI6MTcyMjAwMTI5OH0.iwWc1oYKEBpF81b_9zsX9fUiPt4YgztN8NVDwZutXIc