### login
POST localhost:8080/auth/login
Content-Type: application/json

{
  "username": "username",
  "password": "password@1234"
}

> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}


### createBoard
POST localhost:8080/boards
Content-Type: application/json
Authorization:{{access_token}}

{
  "title": "test board 2"
}

### readBoards
GET localhost:8080/boards

### createNormalPost
POST localhost:8080/boards/1
Content-Type: application/json
Authorization:{{access_token}}

{
  "postType": "NORMAL",
  "title": "test normal post",
  "body": "test normal body"

}

### createReviewPost
POST localhost:8080/boards/1
Content-Type: application/json
Authorization:{{access_token}}

{
  "postType": "REVIEW",
  "title": "test review post",
  "body": "test review body",
  "rating": "5.0"

}

### createContentPost
POST localhost:8080/boards/1
Content-Type: application/json
Authorization:{{access_token}}

{
  "postType": "CONTENT",
  "contentId": 1

}

### readBoard
GET localhost:8080/boards/1

### readPost
GET localhost:8080/boards/1/1

### updatePost
PUT localhost:8080/boards/1/3
Content-Type: application/json
Authorization:{{access_token}}

{
  "boardId": 1,
  "title": "test post 2",
  "body": "test content 2"
}

### deletePost
DELETE localhost:8080/boards/1/3
Authorization:{{access_token}}
