### login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "master",
  "password": "1234"
}

> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}



### 결제 준비
POST localhost:8080/api/payments/kakao
Content-Type: application/json
Authorization:{{access_token}}

{
  "orderId": "ORDER_ID_12",
  "userId": 1,
  "amount": 1000
}

> {%
    pm.environment.set("tid", pm.response.json().tid);
    pm.environment.set("orderId", pm.response.json().orderId);
%}


### 결제 승인 요청
GET localhost:8080/api/payments/kakao/success
Authorization:{{access_token}}

Query Parameters:
- tid: {{tid}}
- orderId: {{orderId}}
- pg_token: {{pg_token}}

> {%
    pm.environment.set("paymentStatus", pm.response.json().status);
%}


### 결제 상태 조회
GET localhost:8080/api/payments/kakao/status
Authorization:{{access_token}}

Query Parameters:
- tid: {{tid}}


### 결제 취소
POST localhost:8080/api/payments/kakao/cancel
Content-Type: application/json
Authorization:{{access_token}}

{
  "tid": "{{tid}}",
  "cancelAmount": "10"
}