###북마크 생성
POST http://localhost:8080/bookmarks/1
Content-Type: application/json
Authorization:{{access_token}}

{
  "userId": 1,
  "message": "Adding bookmark3",
  "status": true
}

###북마크 삭제
DELETE http://localhost:8080/bookmarks/3
Content-Type: application/json
Authorization:{{access_token}}

{
  "userId": 1,
  "message": "Removing bookmark",
  "status": false
}

###북마크 전체 조회
GET http://localhost:8080/bookmarks/user/1
Content-Type: application/json
Authorization:{{access_token}}