### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "username": "username",
  "password": "password@1234",
  "email": "test1@gmail.com"
}

### login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "username",
  "password": "password@1234"
}

> {%
    client.global.set("access_token", response.body.accessToken);
%}


### 모든 크롤링 서비스 시작.
POST localhost:8080/api/content/start/all
Authorization:{{access_token}}

### r
POST localhost:8080/api/content/start/r
Authorization:{{access_token}}
### m
POST localhost:8080/api/content/start/m
Authorization:{{access_token}}
### k
POST localhost:8080/api/content/start/k
Authorization:{{access_token}}

### DB 크롤링 데이터 로컬에 저장.
GET localhost:8080/content/local

### 로컬 크롤링 데이터로 DB 업데이트.
POST localhost:8080/content/local/update

### Content 단건 조회
GET localhost:8080/content?contentUrl=https%3A%2F%2Fridibooks.com%2Fbooks%2F2313041736%3F_rdt_sid%3Dcategory_bestsellers%26_rdt_idx%3D10%26_rdt_arg%3D1750